### ISSUE TITLE
What is the license on this code?

### ISSUE THREAD

**Issue by Kirtai** [pharo-containers/Containers-UniqueOrdered#3]
There doesn't appear to be a license on this code.

**Comment by Kirtai** [comment]
Sorry for spamming so many issues but I'd really like to be able to use these.

**Comment by Ducasse** [comment]
All the code in this repo and projects is MIT.

**Comment by Ducasse** [comment]
There is the token on the first page.

**Comment by Kirtai** [comment]
Ah yes, I see it now. Thank you and sorry for the bother.
